- name: Asegurar que el servicio Nginx está detenido y deshabilitado
  service:
    name: nginx
    state: stopped
    enabled: no

# 2. Desinstalar el paquete Nginx
- name: Desinstalar el paquete Nginx
  apt:
    name: nginx
    state: absent # <-- ¡La clave es usar 'absent'!
    autoremove: yes # <-- Elimina dependencias innecesarias

# 3. Eliminar la página de prueba personalizada (Limpieza)
# NOTA: Esto no elimina archivos de configuración por defecto de Nginx (/etc/nginx)
- name: Eliminar el archivo de prueba index.html
  file:
    path: /var/www/html/index.html
    state: absent # <-- Usa 'absent' para borrar archivos o directorios
