---
- name: Replace /etc/resolv.conf with static content
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Schedule local playbook to run every 10 minutes
  hosts: machines
  ansible.builtin.cron:
    name: "Auto-run NFS Ansible Playbook"
    user: "ansible"
    minute: "*/10"
    job: "cd /mnt/git/ansible_playbooks/playbooks && ANSIBLE_ROLES_PATH=/mnt/git/ansible_playbooks/roles /usr/bin/ansible-playbook /mnt/git/ansible_playbooks/playbooks/master_config.yaml --connection=local -i localhost, >> /var/log/ansible-deployment.log 2>&1"
    state: present
