---
- name: Install required tools and dependencies.
  hosts: machines
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  roles:
  - common

- name: Get latest version of the HAproxy
  hosts: haproxy
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  roles:
  - haproxy
